jdk:
  - openjdk6
  - oraclejdk8
language: scala
env:
  - PROJECT=statsd
  - PROJECT=redis
script: cd util && sbt +publish-local && cd ../$PROJECT && sbt +test
matrix:
  exclude:
  - jdk: openjdk6
    env: PROJECT=redis
  - jdk: oraclejdk8
    env: PROJECT=statsd
services:
  - redis-server
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
sudo: false
